version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["nodejs", "jquery", "browser", "mongo", "jest", "cypress", "mocha", "vitest", "jasmine"]
plugins = ["react", "vue", "ember", "angularjs", "angular"]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true
