name: Codecov

on:
  push:
  pull_request:
    branches: [master]

jobs:
  checkout:
    name: To the moon 🚀🌕
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
