name: Licensed

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: jonabc/setup-licensed@v1
        with:
          version: '4.x'
      - run: npm ci
      - run: licensed status
